export const ANIMATION = {
  CLOSE_DURATION: 600,
  NODE_DELAY: 100,
  VIEW_TRANSITION: 750,
  CONSTELLATION_LAYER_DELAY: 1000,
  ZOOM: {
    INITIAL_SCALE: 2.5,
    INITIAL_DURATION: 500,
    LAYER_DURATION: 1000
  }
};